---
title: "Temp"
author: "Ewout Knoester & Kyra Pikaar" 
date: "24 August 2021"
output: html_document
---

# Setup and data import
```{r setup, include = "FALSE", message = "FALSE", warning = FALSE}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks

library("readxl")
library("tidyverse")
library("lattice")
library("ggpubr")
library("fitdistrplus")
library("latticeExtra")
library("dplyr")
library("lubridate") # Floor dates
```

<!-- 
Data info:
NOAA data is average Sea Surface Temperature of Kenyan coast as measured by satellite imagery
HOBO loggers were attached to PPR frame of 1 intertidal and 1 subtidal structure
HOBO interval for Intertidal experiment was every 10 minutes from 2020-03-18 till 2020-04-11
HOBO interval for Intertidal experiment was every 1 hour from 2020-04-21 till 2020-09-12
Light was logged by HOBO, but loggers weren't regularly cleaned and got overgrown by fouling within days
-->

# Data import and organize
```{r data cleaning}

# NOAA
# load data NOAA (taken from: https://coralreefwatch.noaa.gov/product/vs/data/kenya.txt)
NOAA <- read.table(file = "kenya_2021-08-20.txt", header = TRUE, skip = 21, sep = "")
NOAA$YYYY <- as.Date(paste(NOAA$YYYY, NOAA$MM, NOAA$DD, sep = "-"), format = "%Y-%m-%d") # Merge date to 1 column

# Organize NOAA data
NOAA.1 <- NOAA[c(1,4,5,9)] # Select relevant columns
names(NOAA.1) <- c("Date", "SST.min", "SST.max", "DHW")
NOAA.1 <- as.data.frame(append(NOAA.1, list(SST.avg = (NOAA.1$SST.min + NOAA.1$SST.max)/2), after = 3))

# Select subset with relevant dates
NOAA.2 <- NOAA.1[NOAA.1$Date >= "2019-11-15" & NOAA.1$Date <= "2020-09-12", ]

# HOBO
# Load data HOBO logger
HOBO <- read_excel("HOBO (light & temp)_2021-08.xlsx", sheet = 1)

# Organize HOBO data
HOBO$Experiment <- as.factor(HOBO$Experiment)
HOBO$Treatment <- as.factor(HOBO$Treatment)
HOBO.1 <- HOBO[c(2,3,6,7,8)]
names(HOBO.1) <- c("Experiment", "Treatment", "Date", "Temp", "Light")
HOBO.1 <- HOBO.1[HOBO.1$Experiment == "Intertidal",]
HOBO.1$Date <- floor_date(HOBO.1$Date, unit = "day") # Reduce date and time to date (day) only for selection

# Average per day
HOBO.2 <- HOBO.1 %>%
  group_by(Treatment, Date) %>%
  dplyr::summarize(HOBO.avg = mean(Temp), HOBO.min = min(Temp), HOBO.max = max(Temp), Light = mean(Light), Experiment = Experiment[1])
HOBO.2 <- HOBO.2[-c(6,7)]

# Long to wide: get averages per day split in columns by Treatment
HOBO.avg <- HOBO.2[-c(4,5)]
HOBO.avg <- spread(HOBO.avg, key = Treatment, value = HOBO.avg)
names(HOBO.avg) <- c("Date", "INT.avg", "SUB.avg")
HOBO.avg$Date <- as.Date(HOBO.avg$Date, format = "%Y-%m-%d")

# Join NOAA and HOBO datasets
Temp <- plyr::join(NOAA.2, HOBO.avg, by = "Date")

# Separate data frames for HOBO Min and Max for Intertidal and Subtidal
HOBO.int <- HOBO.2[HOBO.2$Treatment == "Intertidal",]
HOBO.sub <- HOBO.2[HOBO.2$Treatment == "Subtidal",]

```

# Plots
```{r plots}

# Averages NOAA and HOBO + DHW
# Select dates for plotting
Temp.plot <- Temp[Temp$Date >= "2019-11-15" & Temp$Date <= "2020-09-12", ]
Temp.plot$MMM <- 28.7719 + 1 # Set average monthly maximum mean +1 (= bleaching threshold)

library(lattice)
library(latticeExtra)

# Plot in XYPLOT
Temp_graph <- xyplot(data = Temp.plot, SST.max + INT.avg + SUB.avg + MMM ~ Date, 
                     par.settings = list(superpose.line = list(col = c("black", "red"))),
                     col = c("green3", "turquoise", "dodgerblue3", "yellow", "red"),
                     key = list(corner = c(1, 0.95),
                     text = list(c("Temp Int (avg)", "Temp Sub (avg)", "Temp NOAA (max)", "Temp MMM + 1", "DHW")),
                     lines = list(lty = c("solid", "solid", "solid", "twodash", "twodash"), lwd = 3,
                                  col = c("turquoise", "dodgerblue3", "green3", "yellow", "red"))),
                     type = c("l", "g"), # Set type of graph: line graph
                     lty = c("solid", "solid", "solid", "twodash", "twodash"), lwd = c(2, 2.5, 2.5),
                     xlab = "Date", ylab = expression("Temperature " ( degree~C)))

# Plotting Degree Heating Weeks (DHW)
DHW_graph <- xyplot(DHW ~ Date, data = Temp.plot, superpose = T, col="red", lwd = 2, type = "l", lty = 5,
                    xlab = "Date", ylab = "Degree Heating Week (DHW)")

# Combine Temp and DHW
tiff("Temp and DHW.tiff", width = 23, height = 12, units = "cm", res=1200, compression = "lzw")
doubleYScale(Temp_graph, DHW_graph, add.ylab2 = TRUE)
dev.off()

# Min and Max for Intertidal and Subtidal
# Set layout
trellis.par.set(strip.background = list(col = "#DADADA"))
trellis.par.set(axis.text = list(cex = 1, fontface = "bold", col="#000000"))
trellis.par.set(par.xlab.text = list(cex = 1, fontface = "plain", col="#000000"))

# Plotting temperatures
tiff("Min and max.tiff", width = 23, height = 12, units = "cm", res=1200, compression = "lzw")
xyplot(HOBO.max + HOBO.avg + HOBO.min ~ Date | Treatment, data = HOBO.2,
              col=c("red", "gold2", "dodgerblue"), lwd = c(2, 3, 2), 
              key = list(corner = c(1, 0.9), # Position legend
              text = list(c("Maximum", "Average", "Minimum")),
              lines = list(lwd=c(4,6,4), col=c("red", "gold2", "dodgerblue"))),
              type = c("l","g"), 
              xlab="Date", ylab = list(expression("Temperature " ( degree~C)), cex = 1),
              ylim=c(23, 36), layout=c(1,2),  scales=list(y=list(relation="free")))
dev.off()

```

```{r}

library(lattice)
library(latticeExtra)

# Define the date for the vertical line
line_date <- as.Date("2023-12-24")

# Create the temperature plot without any shaded area or custom panels
Temp_graph <- xyplot(SST.max + INT.avg + SUB.avg + MMM ~ Date, 
                     data = Temp.plot, 
                     par.settings = list(superpose.line = list(col = c("green3", "turquoise", "dodgerblue3", "yellow"))),
                     key = list(corner = c(1, 0.95),
                     text = list(c("Temp Int (avg)", "Temp Sub (avg)", "Temp NOAA (max)", "Temp MMM + 1")),
                     lines = list(lty = c("solid", "solid", "solid", "twodash"), lwd = 3,
                                  col = c("turquoise", "dodgerblue3", "green3", "yellow"))),
                     type = c("l", "g"), 
                     lty = c("solid", "solid", "solid", "twodash"), lwd = c(2, 2.5, 2.5),
                     xlab = "Date", ylab = expression("Temperature " ( degree~C)))

# Create the DHW plot
DHW_graph <- xyplot(DHW ~ Date, data = Temp.plot, col = "red", lwd = 2, type = "l", lty = 5,
                    xlab = "Date", ylab = "Degree Heating Week (DHW)",
                    panel.abline(h = 0, col = "red", lty = 2, lwd = 2)
                    )

# Combine Temp and DHW plots
combined_graph <- doubleYScale(Temp_graph, DHW_graph, add.ylab2 = TRUE)

# Add the vertical line at the specified date
final_graph <- update(combined_graph,
                      panel = function(...) {
                          # Draw the vertical line
                          panel.abline(h = 25, col = "red", lty = 2, lwd = 2)
                          # Call the original panel function to draw the plot
                          panel.xyplot(...)
                      })

# Save the final combined plot as PNG
png("Temp_and_DHW.png", width = 23, height = 12, units = "cm", res = 200)
print(final_graph)
dev.off()


```

